[project]
name = "manhattan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "adbc-driver-sqlite>=1.9.0",
    "polars>=1.35.2",
    "pyarrow>=22.0.0",
]
